import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NewHeader from "../components/newHeader";
import EnterLottery from "../components/LotteryEntrance";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Decentralized Lottery</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NewHeader></NewHeader>
            <EnterLottery />
        </div>
    );
}
